version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: devtraining-app
    ports:
      - "3000:3000"
    networks:
      - net
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: devtraining-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - .docker/postgres/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


networks:
  net:
    driver: bridge